# Configuration of Academia
# Documentation: https://sourcethemes.com/academic/
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).
# Title of your site
name: Job Nmadu
# Title of your site
title: Data modelling to develop ...

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseURL: https://jobnmadu.com/

# Enter a copyright falsetice to display in the site footer.
# To display a copyright symbol, type `&copy;`. For current year, type `\{year\}`.
copyright: JNNmadu &copy; {year}

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics: 'G-V53DTDYQF5'

# Enable comments by entering your Disqus shortname
disqusShortname: ''

############################
## Advanced options below ##
############################

# Name of Academic theme folder in `themes/`.
#theme = "hugo-academic"

# Get last modified date for content from Git?
enableGitInfo = true

#search components
enableRobotsTXT = true
cafalsenifyURLs = true

# Default language to use (if you setup multilingual support)
defaultContentLanguage: en
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false

removePathAccents = true  # Workaround for https://github.com/gohugoio/hugo/issues/5687

paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
footfalsetereturnlinkcontents = "<sup>^</sup>"
igfalsereFiles:
  - \\.ipynb$
  - \\.ipynb_checkpoints$
  - \\.Rmd$
  - \\.Rmarkdown$
  - _files$
  - _cache$
  - \\.knit\\.md$
  - \\.utf8\\.md$

outputs:
  home:
    - HTML
    - RSS
    - JSON
    - WebAppManifest
  section:
   - HTML
   - RSS
#  mediaTypes.application/manifest+json:
#  suffixes: webmanifest
 
# outputFormats.WebAppManifest:
#  mediaType: application/manifest+json
#  rel: manifest

# Configure BlackFriday Markdown rendering.
# See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
#[markup]
#  defaultMarkdownHandler: goldmark
#  [markup.goldmark]
#    [markup.goldmark.renderer]
#      unsafe = true  # Enable user to embed HTML snippets in Markdown content.
#  [markup.highlight]
#    codeFences = false  # Disable Hugo's code highlighter as it conflicts with Academic's highligher.
#  [markup.tableOfContents]
#    startLevel = 2
#    endLevel = 3

imaging:
  anchor: smart # Anchor for cropping. Options include Smart and Center.
  resampleFilter = "lanczos"
  quality = 90

# Taxofalsemies.
taxofalsemies:
  author: authors
  category: categories
  publication_type: publication_types
  tag: tags

# module:
#  module.imports:
#    path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy
#  module.imports:
#    path: github.com/wowchemy/wowchemy-hugo-modules/netlify-cms-academic
    
# Workaround Hugo publishing taxofalsemy URLs as plurals - consistently use singular across Wowchemy.
# permalinks:
#  authors: /author/:slug/
#  tags: /tag/:slug/
#  categories: /category/:slug/
#  publication_types: /publication-type/:slug/
